name: "Setup and install"
description: "Setup and install dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - shell: bash
      run: bun install --frozen-lockfile