name: 'Saltman'
description: 'Analyzes PR content and posts results as a comment'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  provider:
    description: 'LLM provider to use for code review. Must be either "openai", "anthropic", or "openai-compatible". OpenAI is recommended.'
    required: true
  api-key:
    description: 'API key for the specified LLM provider.'
    required: true
  base-url:
    description: 'Base URL for OpenAI-compatible API. Required when provider is "openai-compatible".'
    required: false
  model:
    description: 'Model name to use. For OpenAI: gpt-5.1-codex-mini (default), gpt-5.1-codex-max, or gpt-5.2-codex. For Anthropic: claude-opus-4-5 (default), claude-sonnet-4-5 or claude-haiku-4-5. Required when provider is "openai-compatible".'
    required: false
  post-comment-when-no-issues:
    description: 'Whether to post the analysis as a comment on the PR when no issues are detected (true/false). Defaults to false if not specified.'
    required: false
  ignore-patterns:
    description: 'Newline-separated list of glob patterns to ignore files from PR analysis (e.g., "**/*.test.ts\n**/node_modules/**\n*.md"). Similar to .eslintignore or .gitignore patterns.'
    required: false
  target-branch:
    description: 'Branch name to monitor for direct pushes. When set and action is triggered on push event, creates a GitHub issue instead of PR comments. Only used when triggered on push events.'
    required: false
  ping-users:
    description: 'Space or newline-separated list of GitHub usernames or teams to ping (e.g., "@team/security @user1 @user2"). All items must start with "@".'
    required: false
  severity-filter:
    description: 'Newline-separated list of severity levels to include in the review (e.g., "critical\nhigh\nmedium"). Valid values: critical, high, medium, low, info. If unspecified, all severities are shown.'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
    - name: Build
      shell: bash
      run: bun run build
    - name: Run action
      shell: bash
      run: bun dist/main.js
      env:
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
        INPUT_PROVIDER: ${{ inputs.provider }}
        INPUT_API-KEY: ${{ inputs.api-key }}
        INPUT_BASE-URL: ${{ inputs.base-url }}
        INPUT_MODEL: ${{ inputs.model }}
        INPUT_POST-COMMENT-WHEN-NO-ISSUES: ${{ inputs.post-comment-when-no-issues }}
        INPUT_IGNORE-PATTERNS: ${{ inputs.ignore-patterns }}
        INPUT_TARGET-BRANCH: ${{ inputs.target-branch }}
        INPUT_PING-USERS: ${{ inputs.ping-users }}
        INPUT_SEVERITY-FILTER: ${{ inputs.severity-filter }}

