name: 'Saltman'
description: 'Analyzes PR content and posts results as a comment'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
    - name: Build
      shell: bash
      run: bun run build
    - name: Run action
      shell: bash
      run: bun dist/main.js
      env:
        INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}

