import * as core from "@actions/core";
import * as github from "@actions/github";

async function run(): Promise<void> {
  try {
    // Get inputs
    const token = core.getInput("github-token", { required: true });

    // Initialize GitHub client
    const octokit = github.getOctokit(token);
    const context = github.context;

    const owner = context.repo.owner;
    const repo = context.repo.repo;

    // Determine the user to check permissions for
    let username: string;
    let prNumber: number | undefined;

    if (context.payload.pull_request) {
      // PR event - check PR author
      prNumber = context.payload.pull_request.number;
      username = context.payload.pull_request.user.login;
    } else if (context.eventName === "push") {
      // Push event - check the actor who triggered the workflow
      username = context.actor;
      // For push events, we might not have a PR number
      core.info(`Checking permissions for push event by ${username}`);
    } else {
      core.setFailed("This action must be run on a pull request or push event");
      return;
    }

    // Check if user has write access to the repository
    try {
      const { data: permission } = await octokit.rest.repos.getCollaboratorPermissionLevel({
        owner,
        repo,
        username,
      });

      const hasWriteAccess = permission.permission === "write" || permission.permission === "admin";
      
      if (!hasWriteAccess) {
        core.info(`User ${username} does not have write access to ${owner}/${repo}. Skipping action.`);
        return;
      }

      core.info(`User ${username} has ${permission.permission} access. Proceeding with action.`);
    } catch (error) {
      // If we can't check permissions (e.g., user is not a collaborator), skip
      if (error instanceof Error && error.message.includes("404")) {
        core.info(`User ${username} is not a collaborator or does not have write access. Skipping action.`);
        return;
      }
      throw error;
    }

    // If this is not a PR event, we can't proceed with PR analysis
    if (!prNumber) {
      core.info("Push event detected but PR analysis requires a pull request. Skipping.");
      return;
    }

    // Fetch PR details (we know prNumber is defined here due to the check above)
    const { data: pr } = await octokit.rest.pulls.get({
      owner,
      repo,
      pull_number: prNumber!,
    });

    // Fetch PR files
    const { data: files } = await octokit.rest.pulls.listFiles({
      owner,
      repo,
      pull_number: prNumber!,
    });

    // Process/analyze PR content
    const analysis = analyzePR(pr, files);

    // Post comment to PR
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber!,
      body: analysis,
    });

    // Set output
    core.setOutput("result", analysis);

    core.info("Analysis complete and comment posted");
  } catch (error) {
    if (error instanceof Error) {
      core.setFailed(error.message);
    } else {
      core.setFailed("Unknown error occurred");
    }
  }
}

function analyzePR(pr: any, files: any[]): string {
  // Basic analysis - this is where you'd implement your custom logic
  const fileCount = files.length;
  const additions = files.reduce((sum, file) => sum + (file.additions || 0), 0);
  const deletions = files.reduce((sum, file) => sum + (file.deletions || 0), 0);

  return `## PR Analysis

**Title:** ${pr.title}
**Files Changed:** ${fileCount}
**Additions:** +${additions}
**Deletions:** -${deletions}

---
*This analysis was generated by the Saltman GitHub Action*`;
}

// Execute the action
run();
