import * as core from "@actions/core";
import * as github from "@actions/github";

async function run(): Promise<void> {
  try {
    // Get inputs
    const token = core.getInput("github-token", { required: true });

    // Initialize GitHub client
    const octokit = github.getOctokit(token);
    const context = github.context;

    // Ensure this is running on a pull request
    if (!context.payload.pull_request) {
      core.setFailed("This action must be run on a pull request event");
      return;
    }

    const prNumber = context.payload.pull_request.number;
    const owner = context.repo.owner;
    const repo = context.repo.repo;

    // Fetch PR details
    const { data: pr } = await octokit.rest.pulls.get({
      owner,
      repo,
      pull_number: prNumber,
    });

    // Fetch PR files
    const { data: files } = await octokit.rest.pulls.listFiles({
      owner,
      repo,
      pull_number: prNumber,
    });

    // Process/analyze PR content
    const analysis = analyzePR(pr, files);

    // Post comment to PR
    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: analysis,
    });

    // Set output
    core.setOutput("result", analysis);

    core.info("Analysis complete and comment posted");
  } catch (error) {
    if (error instanceof Error) {
      core.setFailed(error.message);
    } else {
      core.setFailed("Unknown error occurred");
    }
  }
}

function analyzePR(pr: any, files: any[]): string {
  // Basic analysis - this is where you'd implement your custom logic
  const fileCount = files.length;
  const additions = files.reduce((sum, file) => sum + (file.additions || 0), 0);
  const deletions = files.reduce((sum, file) => sum + (file.deletions || 0), 0);

  return `## PR Analysis

**Title:** ${pr.title}
**Files Changed:** ${fileCount}
**Additions:** +${additions}
**Deletions:** -${deletions}

---
*This analysis was generated by the Saltman GitHub Action*`;
}

// Execute the action
run();
